[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
# We link to the folder 'core', but the package name inside is 'poker_core'
poker_core = { path = "../core" }
protocol = { path = "../protocol" }
storage = { path = "../storage" }
rand = "0.9.2"
strum = "0.27"
rocket = { version = "0.5.1", features = ["json"] }
ws = { package = "rocket_ws", version = "0.1.1" } 
uuid = { version = "1.0", features = ["v4"] }
futures-util = "0.3"
